import TopHeader from "./Components/TopHeader"
import { NavigationBar } from "./Components/mainHeader";
import { Footer } from "./Components/Footer";
import   {Metadata } from "next";
import "./globals.css"



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className=""
      >
        <TopHeader/>
        <NavigationBar/>
        
        {children}
        <Footer/>
      </body>
    </html>
  );
}
 